version: '2'
services:
    web-dev:
        container_name: web-dev
        image: mfrankiewicz/web-dev
        networks:
            zpw_web_net:
                ipv4_address: 172.16.240.10
        volumes:
            - .:/var/www
        ports:
            - "172.16.240.1:80:80"
    deployd:
        container_name: deployd
        image: mfrankiewicz/deployd
        networks:
            zpw_api_net:
                ipv4_address: 172.16.241.20
        links:
            - mongodb
        ports:
            - "172.16.241.1:80:2403"
        volumes:
            - ./deployd:/src/deployd
        environment:
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
    mongodb:
        container_name: mongodb
        image: library/mongo
        networks:
            zpw_api_net:
                ipv4_address: 172.16.241.30
        ports:
            - "172.16.241.1:27017:27017"
        volumes:
            - ./mongodb:/data/db
networks:
    zpw_web_net:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 172.16.240.0/24
              gateway: 172.16.240.1
    zpw_api_net:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 172.16.241.0/24
              gateway: 172.16.241.1
